name: flucommerce
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  http: ^1.2.2
  iconly: ^1.0.1
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  webview_flutter: ^4.9.0
  url_launcher: ^6.3.0
  loading_animation_widget: ^1.2.1
  another_flushbar: ^1.12.30
  ionicons: ^0.2.2
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Light.ttf
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Bold.ttf

    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
